import { ReactNode } from "react"
import "styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
